Merge nodejs/master
nodejs/node-chakracore pull request #192
Opened 2017-03-17 22:35 UTC by kunalspathak

##### Checklist

- [x] `make -j4 test` (UNIX), or `vcbuild test` (Windows) passes
- [x] commit message follows commit guidelines

##### Affected core subsystem(s)

Merge 5bda5fa as of 03-17-2017

Commit to review:
* 2a2d9d1 : Removed TTD code after refactoring of `node_file.cc`.

2017-03-17 22:36 UTC, kunalspathak commented
@digitalinfinity - can you review?

CI  : https://ci.nodejs.org/job/chakracore-test-windows/43/

2017-03-17 23:36 UTC, digitalinfinity requested changes
LGTM other than the TTD changes...

2017-03-17 23:36 UTC, digitalinfinity commented on src/node_file.cc
> -#if ENABLE_TTD_NODE
These are removed? Is that right? cc @mrkmarron

2017-03-18 00:21 UTC, kunalspathak commented on src/node_file.cc
> -#if ENABLE_TTD_NODE
Yes, Already confirmed from @mrkmarron before removing this.

2017-03-18 00:24 UTC, mrkmarron commented on src/node_file.cc
> -#if ENABLE_TTD_NODE
They are no longer explicitly modifying the raw double* so everything is tracked by the JsRT TTD hooks now.

2017-03-20 17:28 UTC, merged