Small fix for call stack extraction in trace_mgr.js.
nodejs/node-chakracore pull request #492
Opened 2018-03-08 21:45 UTC by mrkmarron

##### Checklist

- [ ] `make -j4 test` (UNIX), or `vcbuild test` (Windows) passes
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message follows [commit guidelines](https://github.com/nodejs/node/blob/master/doc/guides/contributing/pull-requests.md#commit-message-guidelines)

2018-03-08 21:49 UTC, MSLaguana approved these changes

2018-03-09 00:05 UTC, kfarnung approved these changes
LGTM

2018-03-09 00:05 UTC, kfarnung commented on lib/trace_mgr.js
> +  const lastframe = (errstk.length !== 0 ? errstk[errstk.length - 1] : "empty_stack");
Nit: Should we just use `> 0` since it's more explicit?

2018-03-09 00:06 UTC, kfarnung commented
CI: https://ci.nodejs.org/job/chakracore-test-pull-request/214/

2018-03-09 00:09 UTC, kfarnung commented
@mrkmarron Can you update the commit title to conform to the node rules?

* include a subsystem (in this case "lib")
* be shorter than 50 characters
* use a lowercase letter to start and no period

`lib: fix call stack extraction in trace_mgr.js`

2018-03-09 01:03 UTC, kfarnung requested changes
LGTM other than CI errors.

2018-03-09 01:03 UTC, kfarnung commented on lib/trace_mgr.js
> +  const lastframe = (errstk.length !== 0 ? errstk[errstk.length - 1] : "empty_stack");
The CI failed with:

```
19:08:04 not ok 6 - /usr/home/iojs/build/workspace/node-test-linter/lib/trace_mgr.js
19:08:04   ---
19:08:04   message: Line 491 exceeds the maximum line length of 80.
19:08:04   severity: error
19:08:04   data:
19:08:04     line: 491
19:08:04     column: 1
19:08:04     ruleId: max-len
19:08:04   messages:
19:08:04     - message: Strings must use singlequote.
19:08:04       severity: error
19:08:04       data:
19:08:04         line: 491
19:08:04         column: 72
19:08:04         ruleId: quotes
19:08:04   …
```

2018-05-01 21:39 UTC, kfarnung approved these changes

2018-05-01 21:41 UTC, kfarnung commented
New CI: https://ci.nodejs.org/job/chakracore-test-pull-request/252/

2018-05-01 22:11 UTC, kfarnung commented
@MSLaguana looks like the Ubuntu CI hit a seg fault: https://ci.nodejs.org/job/chakracore-test-linux/370/nodes=ubuntu1604-64/console

2018-05-01 22:19 UTC, kfarnung commented
Linux rerun: https://ci.nodejs.org/job/chakracore-test-linux/371/

2018-05-01 22:57 UTC, kfarnung commented
@MSLaguana it is consistent about where at least: https://ci.nodejs.org/job/chakracore-test-linux/371/nodes=ubuntu1404-64/console

2018-05-01 22:58 UTC, merged

2018-05-01 22:58 UTC, kfarnung commented
Landed in 5e5a96c1003816fb63a7cfafc671a4ee53583b80