Fix for context leak.
nodejs/node-chakracore pull request #564
Opened 2018-07-09 17:42 UTC by mrkmarron

Fix for leak of contexts by naked addref (instead use TTD aware API). 

##### Checklist

- [x] `make -j4 test` (UNIX), or `vcbuild test` (Windows) passes

2018-07-09 17:48 UTC, kfarnung commented
CI: https://ci.nodejs.org/job/chakracore-test-pull-request/278/

2018-07-09 17:49 UTC, kfarnung approved these changes
LGTM pending CI

2018-07-09 18:03 UTC, sethbrenith approved these changes
:shipit:

2018-07-09 18:18 UTC, kfarnung commented
The CI isn't very happy, running a baseline CI to investigate:  https://ci.nodejs.org/job/chakracore-test/372/

2018-07-09 21:48 UTC, kfarnung commented
@mrkmarron It looks like `JsTTDNotifyLongLivedReferenceAdd` does not have a handler for `TaggedInt` and it's causing a failfast:

```
02 00000037`f8afe770 00007ff8`30488b7d ChakraCore!ReportFatalException+0x27 [e:\github\node-chakracore2\deps\chakrashim\core\lib\common\exceptions\reporterror.cpp @ 21] 
03 (Inline Function) --------`-------- ChakraCore!Js::RecyclableObject::FromVar+0xe2 [e:\github\node-chakracore2\deps\chakrashim\core\lib\runtime\types\recyclableobject.inl @ 30] 
04 (Inline Function) --------`-------- ChakraCore!JsTTDNotifyLongLivedReferenceAdd::__l2::<lambda_af4dbb55da17447451af4a97397bfc96>::operator()+0x109 [e:\github\node-chakracore2\deps\chakrashim\core\lib\jsrt\jsrt.cpp @ 4177] 
05 (Inline Function) --------`-------- ChakraCore!GlobalAPIWrapper::__l2::<lambda_0fc3edbdae5f0172fa970d023e170d33>::operator()+0x110 [e:\github\node-chakracore2\deps\chakrashim\core\lib\jsrt\jsrtinternal.h @ 152] 
06 00000037`f8afe7d0 00007ff8`3047b030 ChakraCore!GlobalAPIWrapper_Core<<lambda_0fc3edbdae5f0172fa970d023e170d33> >+0x12d [e:\github\node-chakracore2\deps\chakrashim\core\lib\jsrt\jsrtinternal.h @ 127] 
07 (Inline Function) --------`-------- ChakraCore!GlobalAPIWrapper+0x2a [e:\github\node-chakracore2\deps\chakrashim\core\lib\jsrt\jsrtinternal.h @ 150] 
08 00000037`f8afe820 00007ff7`e501726e ChakraCore!JsTTDNotifyLongLivedReferenceAdd+0x40 [e:\github\node-chakracore2\deps\chakrashim\core\lib\jsrt\jsrt.cpp @ 4169] 
09 (Inline Function) --------`-------- node!jsrt::ContextShim::InitializeBuiltIn+0x58 [e:\github\node-chakracore2\deps\chakrashim\src\jsrtcontextshim.cc @ 179] 
0a 00000037`f8afe870 00007ff7`e50162ca node!jsrt::ContextShim::InitializeBuiltIns+0x12e [e:\github\node-chakracore2\deps\chakrashim\src\jsrtcontextshim.cc @ 286] 
0b 00000037`f8afe9a0 00007ff7`e5016513 node!jsrt::ContextShim::DoInitializeContextShim+0x8a [e:\github\node-chakracore2\deps\chakrashim\src\jsrtcontextshim.cc @ 361] 
0c 00000037`f8afea20 00007ff7`e501f34d node!jsrt::ContextShim::EnsureInitialized+0x13 [e:\github\node-chakracore2\deps\chakrashim\src\jsrtcontextshim.cc @ 396] 
0d (Inline Function) --------`-------- node!jsrt::IsolateShim::PushScope+0x2d [e:\github\node-chakracore2\deps\chakrashim\src\jsrtisolateshim.cc @ 466] 
0e 00000037`f8afea50 00007ff7`e5025047 node!jsrt::IsolateShim::PushScope+0x7d [e:\github\node-chakracore2\deps\chakrashim\src\jsrtisolateshim.cc @ 453] 
0f 00000037`f8afea80 00007ff7`e521a77d node!v8::Context::Scope::Scope+0x47 [e:\github\node-chakracore2\deps\chakrashim\src\v8context.cc @ 36] 
10 00000037`f8afeab0 00007ff7`e52200d0 node!node::NewContext+0x4d [e:\github\node-chakracore2\src\node.cc @ 3636] 
11 00000037`f8afebb0 00007ff7`e521fa62 node!node::Start+0x80 [e:\github\node-chakracore2\src\node.cc @ 3666] 
12 (Inline Function) --------`-------- node!node::Start+0xdd [e:\github\node-chakracore2\src\node.cc @ 3888] 
13 00000037`f8affa70 00007ff7`e500e89c node!node::Start+0x492 [e:\github\node-chakracore2\src\node.cc @ 3994] 
14 00000037`f8affba0 00007ff7`e561e020 node!wmain+0x1bc [e:\github\node-chakracore2\src\node_main.cc @ 72] 
```

Can you investigate?

2018-07-09 22:54 UTC, mrkmarron commented
Ack, yes that is my mistake. There is a change in the merged PR #5409 to ChakraCore release/1.10 that fixes this.

2018-07-09 22:57 UTC, kfarnung commented
Ahh, ok, let's wait for ChakraCore 1.10 to land first.

2018-07-09 22:57 UTC, kfarnung requested changes
Waiting for ChakraCore 1.10 and a clean CI run

2018-07-11 18:27 UTC, kfarnung approved these changes
Running a CI then I'll land this.

2018-07-11 21:02 UTC, kfarnung commented
Landed in 2fb23a71056976f95cee00dfe2a065286e61cdfa

2018-07-11 21:02 UTC, closed without merging